extraction:
  cpp:
    after_prepare: 
      - python report.py 119
  cobol:
    after_prepare: 
      - python report.py 119
  csharp:
    after_prepare: 
      - python report.py 119
  java:
    after_prepare: 
      - python report.py 119
  javascript:
    after_prepare: 
      - python report.py 119
  python:
    after_prepare: 
      - python report.py 119
